apiVersion: apps/v1
kind: ReplicaSet
metadata:
  annotations:
    description: Learn running ReplicaSet kubernetes
  labels:
    env: dev
  name: rs-sample
  namespace: dev
spec:
  replicas: 3
  selector:
    matchLabels:
      env: dev
  template:
    metadata:
      labels:
        env: dev
    spec:
      containers:
      - image: nginx
        name: rs-sample
